---

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:

  - os_server:
         state: present
         name: "{{ servername|default('myserver')}}"
         image: "CloudVPS Ubuntu 14.04"
         key_name: demo_pubkey
         timeout: 200
         flavor: 111
         network: net-public
         meta:
           hostname: "{{servername|default('myserver')}}"
           group: "{{servergroup|default('defaultgroup')}}"

